services:
  - type: web
    name: water-tank-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    rootDir: backend
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
    region: singapore

  - type: web
    name: water-tank-monitoring-1
    env: static
    buildCommand: npm install && npm run build
    startCommand: npx serve dist -l $PORT
    rootDir: frontend
    envVars:
      - key: NODE_VERSION
        value: "18"
      - key: VITE_API_URL
        value: "https://water-tank-api.onrender.com"
    region: singapore
